# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "Azure OpenAPI"

trigger: none


jobs:
- template: .azure-pipelines/YamlFileValidetor.yaml
- template: .azure-pipelines/YamlFileValidetor1.yaml
